---
language: ruby
sudo: false
cache: bundler
before_install: gem install bundler -v 1.17
before_script: RAILS_ENV=test bundle exec rake db:create db:schema:load

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/rails4.2_graphql1.8.gemfile
  - gemfiles/rails5.0_graphql1.8.gemfile
  - gemfiles/rails5.0_graphql1.9.gemfile
  - gemfiles/rails5.1_graphql1.8.gemfile
  - gemfiles/rails5.1_graphql1.9.gemfile
  - gemfiles/rails5.2_graphql1.8.gemfile
  - gemfiles/rails5.2_graphql1.9.gemfile

jobs:
  include:
    - gemfile: gemfiles/rails6.0_graphql1.8.gemfile
      rvm: 2.5.7
    - gemfile: gemfiles/rails6.0_graphql1.8.gemfile
      rvm: 2.6.5
    - gemfile: gemfiles/rails6.0_graphql1.9.gemfile
      rvm: 2.5.7
    - gemfile: gemfiles/rails6.0_graphql1.9.gemfile
      rvm: 2.6.5
    - gemfile: gemfiles/rails_edge_graphql_edge.gemfile
      rvm: 2.5.7
    - gemfile: gemfiles/rails_edge_graphql_edge.gemfile
      rvm: 2.6.5
  allow_failures:
    - rvm: 2.5.7
      gemfile: gemfiles/rails_edge_graphql_edge.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_edge_graphql_edge.gemfile
